require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'
install! 'cocoapods', :deterministic_uuids => false

target 'robert_project' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  def fix_fb_react_native_spec(installer)
        installer.pods_project.targets.each do |target|
          if target.name == 'FBReactNativeSpec'
            target.build_configurations.each do |config|
              if config.name == 'Debug' or config.name == 'Release'
                config.build_settings['NODE_BINARY'] = '/opt/homebrew/bin/node'

              end
            end
          end
        end
      end

  target 'robert_projectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    fix_fb_react_native_spec(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
